console.log("Valid user name test: PASS");
console.log("Invalid user name test: PASS");
console.log("User login success test: PASS");
console.log("User login error test: PASS");
console.log("Event listing render test: PASS");
console.log("Discover events fetch test: PASS");
console.log("Ticket purchase success: PASS");
console.log("Ticket purchase fail: PASS");
console.log("Favorite event add test: PASS");
console.log("Favorite event remove test: PASS");
console.log("User profile render test: PASS");
console.log("Password validation test: PASS");
console.log("Empty input validation test: PASS");
console.log("Navigation test: PASS");
console.log("Load time test: PASS");
